### ISSUE TITLE
Does not support IE8

### ISSUE THREAD

**Issue by Fallstop** [LaSpruca/div.center#1]
help, can't center div
![image](https://user-images.githubusercontent.com/43323210/147404719-ef4677b5-2440-4e42-a3a9-921e904c4138.png)
browser: web
brand: windows
architecture: phone
time: now
why: idk, but I take this failure personally

**Comment by LaSpruca** [comment]
Get gud

**Comment by Fallstop** [comment]
thank, it works now

**Comment by Fallstop** [comment]
![image](https://user-images.githubusercontent.com/43323210/147404881-d458fd5a-d7e9-47ef-95e8-850e5a3d8637.png)
got gud, now works on my machine

**Comment by LaSpruca** [comment]
Well done
