### ISSUE TITLE
Doesn't work with curl

### ISSUE THREAD

**Issue by jacobtread** [LaSpruca/div.center#2]
Doesn't work in the command line with curl

**Comment by jacobtread** [comment]
Please add statically rendered centering

**Comment by jacobtread** [comment]
Pixel.jpg will work well for that

**Comment by Fallstop** [comment]
The IE8 workaround works for curl too. Just get gud, the library is perfect

**Comment by LaSpruca** [comment]
> Pxel.jpg will work well for that

no.

Unforgettably, this library does not support SSR, you would be required to SSR the components yourself, this is a JS library designed for the browser, and thus, implementing SSR is not possible.

 As @Fallstop mentioned, the IE8 workarround mentioned in issue #1 works well for curl.
